name: ci

on: [push, pull_request]

jobs:
  rust:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-20.04, windows-2019]

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install clippy and rustfmt
        run: |
          rustup component add clippy
          rustup component add rustfmt

      - name: Build
        run: cargo build --all-targets

      - name: Test
        run: cargo test --all-targets

      - name: Lint
        run: cargo clippy --all-targets
