name: ci

on: [push, pull_request]

jobs:
  rust:
    name: node-resolved-${{ matrix.os }}
    if: |
      github.event_name == 'push' ||
      !startsWith(github.event.pull_request.head.label, 'denoland:')
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-20.04, windows-2019]

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install clippy and rustfmt
        run: |
          rustup component add clippy
          rustup component add rustfmt

      - name: Build
        run: cargo build --all-targets

      - name: Test
        run: cargo test --all-targets

      - name: Lint
        run: cargo clippy --all-targets
